server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coursedb
    username: postgres
    password: reddy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
